create database EMDB
use EMDB
create TABLE EVENT_TBL (
	EVENT_ID INTEGER NOT NULL PRIMARY KEY,
	BEGIN_TIME DATE NOT NULL,
	END_TIME DATE NOT NULL,
)
create TABLE GUEST_TBL(
	GUEST_ID INTEGER NOT NULL PRIMARY KEY,
	GUEST_NAME VARCHAR(50) NOT NULL,
	GUEST_TELE INTEGER UNIQUE,
	GUEST_ADDR VARCHAR(50),
	EVENT_ID INTEGER NOT NULL UNIQUE,

	CONSTRAINT CHK_GUEST_TELE CHECK(GUEST_TELE > 0),
	CONSTRAINT EVENT_ID_FK FOREIGN KEY(EVENT_ID) REFERENCES EVENT_TBL(EVENT_ID)
)
create TABLE ITEM(
	ITEM_ID INTEGER NOT NULL PRIMARY KEY,
	ITEM_COST MONEY NOT NULL,
	EVENT_ID INTEGER NOT NULL UNIQUE, 

	CONSTRAINT CHK_ITEM_COST CHECK(ITEM_COST > 0),
	CONSTRAINT EVET_ID_FK FOREIGN KEY(EVENT_ID) REFERENCES EVENT_TBL(EVENT_ID)
)